name: quizcinese
description: Un semplice generatore di quiz basati su domande memorizzate una base di conoscenza di parole e pittogrammi JSON.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  shared_preferences: ^2.5.5
  flutter_svg: ^2.0.10+1
  confetti: ^0.8.0
  audioplayers: ^6.6.0
  package_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  gh_pages: ^0.1.1
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/questions.json
    - assets/logo.svg
    - assets/libri_cute.svg
    - assets/success.mp3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#ffffff"
    theme_color: "#fff9fb"

